# Generated by Django 3.0.7 on 2020-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpendItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemUser', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=4)),
                ('ItemTime', models.CharField(max_length=32)),
                ('ItemType', models.CharField(max_length=1)),
                ('remarks', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='IncomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemUser', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=4)),
                ('ItemTime', models.CharField(max_length=32)),
                ('ItemType', models.CharField(max_length=1)),
                ('remarks', models.CharField(max_length=48)),
            ],
        ),
    ]
