# Generated by Django 3.0.7 on 2020-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200623_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='goal_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_income', models.CharField(max_length=4)),
                ('goal_expend', models.CharField(max_length=4)),
                ('goal_User', models.CharField(max_length=32)),
                ('goalTime', models.CharField(max_length=32)),
            ],
        ),
    ]
